name: production publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: get the code
        uses: actions/checkout@v2
      - name: build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build"
      - name: prepare to upload to google cloud storage
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.gcp_credentials }}
          export_default_credentials: true
          project_id: ${{ secrets.gcp_project_id }}
      - name: publish to google cloud storage
        run: "gsutil -m -h 'Cache-Control: public, max-age=31536000' rsync -r -d -c ${{ github.workspace }}/_site gs://imgs.surf-station.com"
      - name: update object metadata
        run: "gsutil -m setmeta -h 'Content-Type: text/html; charset=utf-8' -h 'Cache-Control: no-cache, max-age=0' gs://imgs.surf-station.com/**.html"
