name: Jekyll site CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: get the code
        uses: actions/checkout@v2
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build"
      - name: publish to google cloud storage
        uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: ${{ github.workspace }}/_site
          destination: imgs.surf-station.com
